/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jin_jni_JniLoad */

#ifndef _Included_com_jin_jni_JniLoad
#define _Included_com_jin_jni_JniLoad
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jin_jni_JniLoad
 * Method:    what
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jin_jni_JniLoad_what
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
